<template>
<div class="wrapper" ref="wrapper">
 <ul class="mul">
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
   <li>分类</li>
 </ul>

</div>

</template>

<script>
import Bscroll from 'better-scroll'
export default {
  name:'Catgory',
  data(){
    return{
      scroll:null
    }
  },
  created(){
   
  },
  mounted(){
    this.scroll = new Bscroll(this.$refs.wrapper,{

    })
  }
}
</script>

<style>
.wrapper{
  height: 300px;
  background-color: #e6e7;
  overflow: hidden;
}
</style>